// v2/AiRunAndRead_CLAUDE.js
// Claude(および GPT / Gemini)が ai-desk v2 で作業するときのエントリ routing
//
// ⚠️ ファイル名 prefix `AiRunAndRead_` の意味:
//   1. `node AiRunAndRead_CLAUDE.js` で実行 → routing instruction を出力
//   2. or `import { ReadingOrder, Premise, V1Relation } from './AiRunAndRead_CLAUDE.js'`
//   ⛔ .js ソースを prose として linear に読むな
//
// **canonical form**: this file (.js) ← REAL

export const VERSION = "2.6";
export const DATE = "2026-05-04";

export const Folder = {
  identity: "ai-desk v2(All-as-Block, Versions-as-Body)",
  description: [
    "v2 は v1 の原理を単一の抽象(Block)に畳み込んだ実装",
    "すべてが Block。Block の本体は versions の羅列(REAL)、現在の状態は派生(SHADOW)",
  ],
};

// ============================================================
// 読書順序(優先度順、上から読む)
// ============================================================
export const ReadingOrder = [
  { rank: 1, file: 'AiRunAndRead_BIBLE.js',      purpose: '思想の正典(公理 A0〜A8 + Physics + BlockSchema + Taboos + Rituals)' },
  { rank: 2, file: 'AiRunAndRead_ONBOARDING.js', purpose: 'LLM の作業ルール集(禁忌 / Block ops / Graph ops / Constraint / Observation)' },
  { rank: 3, file: 'AiRunAndRead_MANUAL.js',     purpose: '操作マニュアル(workflow / Virtual Heavy Function APPLY)' },
  { rank: 4, file: 'ai-desk.js',                  purpose: '唯一の実装ファイル(Zero-Dep、~2k 行、AiRunAndRead_BIBLE.js を import)' },
  { rank: 5, file: 'e2e.js',                      purpose: '111 テスト(bible-* CLI 4 件含む)' },
];

// ============================================================
// 想定読者(LLM 専用宣言)
// ============================================================
export const Audience = {
  primary: "LLM(Claude / GPT / Gemini / 等)",
  human_role: "supervisor。命令と判断のみ。.js を直接読まない。",
  rationale:
    "人間時代の『読みやすさ』(抽象化・分割・カプセル化)は AI にとって情報の隠匿。" +
    "本リポは逆方向 — 展開・明示・統合された複雑性に最適化されている。" +
    "AI 用ドキュメントは .md でなく AiRunAndRead_*.js が canonical。",
};

// ============================================================
// v1(legacy)との関係
// ============================================================
export const V1Relation = {
  layout: {
    repo_root:   '/PJs/ai-desk/',
    v1_main:     '../ai-desk-old-v1.js',
    v1_docs:     '../AI_NATIVE_MASTER_BIBLE.md など、リポルート配下',
    v2_canonical:'./',
  },
  rules: [
    "v1 のファイルは触らない、固定された過去として保持",
    "v2 で作業するときは v2 の正典(AiRunAndRead_BIBLE.js)に従う",
  ],
};

// ============================================================
// 作業の前提(これだけは即座に内面化する)
// ============================================================
export const Premise = [
  "すべて Block 抽象で動く(Block { id, type, versions, meta })",
  "マーカー(// [ai_s_emblem:...])は新規に書かない、tags は // @tags: で書く",
  "TypeScript・build・依存ライブラリは禁忌",
  "Block.versions は append-only(commit() 経由のみ)",
  "Block.content / refs / tags は SHADOW(getter から都度取得、変数化しない)",
];

// ============================================================
// 関連ツール / 隣接 module
// ============================================================
export const NeighborModules = {
  '3dplus/':   '3D を扱うコードを書く時の CPU Twin(81 tests, CommonJS)',
  'eyes/':     'AI-Eyes 観測ハーネス(in-memory virtual canvas、draw_op log を Block 化)',
  'demos/':    'v2 思想を体現する demo 群(gravity-battle / block-spreadsheet / node-graph / kanban)',
};

// ============================================================
// Self-display + export-md
// ============================================================
export function exportMarkdown() {
  const out = [];
  out.push(`# Claude entry — ai-desk v2`);
  out.push(`> Auto-generated from AiRunAndRead_CLAUDE.js — DO NOT EDIT THIS FILE DIRECTLY.`);
  out.push(`> Run \`node v2/AiRunAndRead_CLAUDE.js export-md > CLAUDE.md\` to regenerate.`);
  out.push(`> Date: ${DATE}\n`);

  out.push(`## このフォルダは ${Folder.identity}`);
  for (const d of Folder.description) out.push(d);
  out.push('');

  out.push(`## 読書順序(上から)`);
  for (const r of ReadingOrder) out.push(`${r.rank}. **${r.file}** — ${r.purpose}`);
  out.push('');

  out.push(`## 想定読者`);
  out.push(`- primary: ${Audience.primary}`);
  out.push(`- human role: ${Audience.human_role}`);
  out.push(`- rationale: ${Audience.rationale}\n`);

  out.push(`## v1(legacy)との関係`);
  out.push(`### layout`);
  for (const [k, v] of Object.entries(V1Relation.layout)) out.push(`- **${k}**: ${v}`);
  out.push(`### rules`);
  for (const r of V1Relation.rules) out.push(`- ${r}`);
  out.push('');

  out.push(`## 作業の前提`);
  for (const p of Premise) out.push(`- ${p}`);
  out.push('');

  out.push(`## 隣接 module`);
  for (const [k, v] of Object.entries(NeighborModules)) out.push(`- **${k}**: ${v}`);

  return out.join('\n');
}

if (typeof process !== 'undefined' && /AiRunAndRead_CLAUDE\.js$/.test(process.argv[1] || '')) {
  if (process.argv[2] === 'export-md') {
    process.stdout.write(exportMarkdown());
  } else {
    console.log(`\n##  AiRunAndRead_CLAUDE.js v${VERSION}  ##\n`);
    console.log(`folder: ${Folder.identity}\n`);
    console.log(`reading order:`);
    for (const r of ReadingOrder) console.log(`  ${r.rank}. ${r.file} — ${r.purpose}`);
    console.log(`\npremise:`);
    for (const p of Premise) console.log(`  - ${p}`);
    console.log(`\nUsage:`);
    console.log(`  node AiRunAndRead_CLAUDE.js export-md > CLAUDE.md`);
    console.log(`  import { ReadingOrder, Premise } from './AiRunAndRead_CLAUDE.js'`);
  }
}
