// Package crystallize — Phase 1 prototype of Block → Go transcription
//
// 5-stage flow position: SHADOW (Go source generated by AI from REAL = JS Block.content)
//
// Source(REAL): ai-desk-core.js export function hashVersion(v) { ... }
//
// JS original:
//   export function hashVersion(v) {
//     const { hash, ...rest } = v;
//     const stable = JSON.stringify(rest, Object.keys(rest).sort());
//     let h = 0x811c9dc5;
//     for (let i = 0; i < stable.length; i++) {
//       h ^= stable.charCodeAt(i);
//       h = (h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))) >>> 0;
//     }
//     return h.toString(16).padStart(8, '0');
//   }
//
// 翻訳の決定事項(transcription contract):
//  - JS の `v` は dynamic object(任意フィールド)→ Go では map[string]any
//  - `const { hash, ...rest } = v` は「hash key を除いた残り」→ Go では key 削除
//  - JSON.stringify の 2nd arg = key array → JSON のキー order 固定 → Go では sort key + 自前 emit
//  - JS の charCodeAt は UTF-16 code unit → Go は rune (UTF-32-ish)、ただし JSON 内は ASCII 中心
//    で問題なし、必要なら utf-16 化を入れる
//  - >>> 0 は unsigned 32-bit、Go では uint32 で同じセマンティクス

package main

import (
	"fmt"
	"sort"
	"strings"
)

// HashVersion: JS hashVersion の Go 翻訳。
// 入力 v は任意 key/value(JS object に相当)。"hash" key は除外して計算。
// 戻り値は 8 文字の lowercase hex(JS と完全一致)。
func HashVersion(v map[string]any) string {
	// Step 1: 'hash' key を除外して残りを取り出す
	rest := map[string]any{}
	for k, val := range v {
		if k != "hash" {
			rest[k] = val
		}
	}
	// Step 2: stable JSON 化(key を sort、JS の `JSON.stringify(rest, Object.keys(rest).sort())` と一致)
	stable := stableJSONStringify(rest)
	// Step 3: FNV-1a 32-bit
	h := uint32(0x811c9dc5)
	for i := 0; i < len(stable); i++ {
		h ^= uint32(stable[i])
		// JS: h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24)) >>> 0
		// 注: JS の `>>> 0` で unsigned 32-bit に丸め。Go の uint32 は同じ semantic で自動 wrap。
		h = h + ((h << 1) + (h << 4) + (h << 7) + (h << 8) + (h << 24))
	}
	// Step 4: 8 文字 lowercase hex
	return fmt.Sprintf("%08x", h)
}

// stableJSONStringify: JS の `JSON.stringify(obj, Object.keys(obj).sort())` 同等出力。
// - key sort
// - 空白なし
// - エスケープは JS と完全一致(ASCII 中心、unicode は問題ないと仮定)
//
// 注意: 完全な JSON.stringify を実装するのではなく、JS hashVersion が呼ばれる
// 文脈(makeVersion 内)で発生する Version オブジェクトの形だけ正しく扱えれば十分。
// 必要に応じて拡張する。
func stableJSONStringify(obj map[string]any) string {
	keys := make([]string, 0, len(obj))
	for k := range obj {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var sb strings.Builder
	sb.WriteByte('{')
	for i, k := range keys {
		if i > 0 {
			sb.WriteByte(',')
		}
		sb.WriteString(jsonString(k))
		sb.WriteByte(':')
		sb.WriteString(jsonValue(obj[k]))
	}
	sb.WriteByte('}')
	return sb.String()
}

func jsonValue(v any) string {
	switch val := v.(type) {
	case nil:
		return "null"
	case bool:
		if val {
			return "true"
		}
		return "false"
	case string:
		return jsonString(val)
	case int:
		return fmt.Sprintf("%d", val)
	case int64:
		return fmt.Sprintf("%d", val)
	case float64:
		// JSON spec: 整数値は整数表記、それ以外は通常表記
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case []any:
		var sb strings.Builder
		sb.WriteByte('[')
		for i, e := range val {
			if i > 0 {
				sb.WriteByte(',')
			}
			sb.WriteString(jsonValue(e))
		}
		sb.WriteByte(']')
		return sb.String()
	case map[string]any:
		// nested objects: JS の JSON.stringify は同 sort 規則を再帰適用
		// ただし JSON.stringify の 2nd arg(key list)は top-level だけ。
		// nested key は inserted order になる。crystallize では sort 統一で安全側に倒す。
		return stableJSONStringify(val)
	default:
		return jsonString(fmt.Sprint(v))
	}
}

func jsonString(s string) string {
	var sb strings.Builder
	sb.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			sb.WriteString(`\"`)
		case '\\':
			sb.WriteString(`\\`)
		case '\n':
			sb.WriteString(`\n`)
		case '\r':
			sb.WriteString(`\r`)
		case '\t':
			sb.WriteString(`\t`)
		case '\b':
			sb.WriteString(`\b`)
		case '\f':
			sb.WriteString(`\f`)
		default:
			if r < 0x20 {
				fmt.Fprintf(&sb, `\u%04x`, r)
			} else {
				sb.WriteRune(r)
			}
		}
	}
	sb.WriteByte('"')
	return sb.String()
}
